### ISSUE TITLE
Run tests verbosely in CircleCI

### ISSUE THREAD

**Issue by chrisbouchard** [chrisbouchard/easyrepr#19]
We can afford some extra noise in the CI logs. It would be nice to see the list of tests that were run (rather than just the count per suite).

**Comment by Xander23432** [comment]
Can you please suggest some resources from where i can learn a bit more about what your project is all about.
As far as I have understood, it is a CI library which shows dynamic logs of the program while running and testing.

**Comment by Xander23432** [comment]
And also if there are some resources which can help me deep dive into the technologies which you have used to create your project.

**Comment by chrisbouchard** [comment]
Hi, @Xander23432. :wave: 

> As far as I have understood, it is a CI library which shows dynamic logs of the program while running and testing.

I'm very interested in what gave you that impression, because this project doesn't have much to do with that at all. I would like to improve my README and tags to make it clearer what the library is for.

As for documentation, your best bet is [the project's page on Read the Docs](https://easyrepr.readthedocs.io/en/latest/)&nbsp;&mdash; that describes the library from a user perspective. It's linked in the README, but I appreciate that it's only as a badge. I'll update that soon to make the documentation more prominent.

I don't have have much in the way of documentation about the technologies yet. I should probably add a CONTRIBUTING document to describe development, testing, and building. The project is using stock Python, and Circle CI for, well, CI.

**Comment by chrisbouchard** [comment]
I've created #20 to track improving the documentation, and I'll try to get to that soon.
